### ISSUE TITLE
Moving up/down is very smooth; moving right jitters and is buggy

### ISSUE THREAD

**Issue by dz4va** [corpusc/viscript#102]

**Comment by corpusc** [comment]
I have never, ever seen this happen.
It makes me wonder if the problem was fully described.
HaltingState did not give me an answer when I asked him for details about it.
Has anyone else seen it?

**Comment by dz4va** [comment]
Yes, @corpusc not sure about that, I didn't get the problem fully. maybe let's ask again

**Comment by corpusc** [comment]
asked again in WeChat.
