### ISSUE TITLE
Focusing bug

### ISSUE THREAD

**Issue by dz4va** [corpusc/viscript#124]
Described with pictures 
![screenshot_20170623234554](https://user-images.githubusercontent.com/5410669/27498454-1c63920a-5870-11e7-8e4c-c0059cf38d28.png)
![screenshot_20170623235142](https://user-images.githubusercontent.com/5410669/27498455-1c6657f6-5870-11e7-9ae0-dfba3defd051.png)

**Comment by corpusc** [comment]
fixed.  but not committed yet, as i'm deep into the new backscroll code (also uncommitted)
