### ISSUE TITLE
Update package.sh to compile skywire/cmd/mesh 

### ISSUE THREAD

**Issue by gz-c** [corpusc/viscript#128]
viscript/mesh/run_mesh was moved to skywire/cmd/mesh.

package.sh used to compile mesh/run_mesh, now it will need to clone the skywire repo and compile skywire/cmd/mesh.

package.sh already clones the skycoin repo and compiles the skycoin binary from it, so it can do the same for the skywire repo and its mesh cmds.

I notice these line in package.sh:
```sh
# Get all dependencies for skycoin.go
pv "Getting all dependencies for Skycoin"
go get -d ./...
```

This should not be necessary since we vendor all dependencies now.  It might even cause a problem on the local machine after running this.  Please verify that it is not needed, and remove it.

**Comment by dz4va** [comment]
Should we instead use skycoin and skywire from vendor/ ?

**Comment by dz4va** [comment]
Because I noticed skywire has a localSkywirePath too so that's all good I think. If we should use vendor/ then we have to make some minor changes in packaging script

**Comment by dz4va** [comment]
In then past that was the way to do it, I'll try to update packaging script

**Comment by gz-c** [comment]
**Do not vendor skywire**

**Comment by dz4va** [comment]
finished
